---
- hosts: all
  remote_user: root
  tasks:
  - name: get conntrack max
    command: cat /proc/sys/net/ipv4/netfilter/ip_conntrack_max
    always_run: yes
    changed_when: false
    register: conntrackd_hash_limit
    when: redundant_state != "UNKNOWN"

  - name: fix logrotate
    copy: src=files/{{ item }}-logrotate dest=/etc/logrotate.d/{{ item }}
    with_items:
    - conntrackd
    - rsyslog
    notify: run logrotate

  - name: fix conntrackd config
    template: src=files/conntrackd.conf.j2 dest=/etc/conntrackd/conntrackd.conf
    when: redundant_state != "UNKNOWN"
    notify:
    - restart conntrackd
    - restart rsyslog

  - name: stop conntrackd on non-redundant routers
    service: name=conntrackd state=stopped
    when: redundant_state == "UNKNOWN"

  - name: load nf modules
    command: modprobe {{ item }}
    with_items:
    - nf_conntrack_ftp
    - nf_nat_ftp
    changed_when: false

  - name: load nf modules
    template: src=files/modules dest=/etc/modules

  - name: make apache threads nicer periodically
    cron: name="metadata api" minute="*/20" job="renice 19 -u www-data"

  handlers:
  - name: restart conntrackd
    service: name=conntrackd state=restarted

  - name: restart rsyslog
    service: name=rsyslog state=restarted

  - name: run logrotate
    command: logrotate -f /etc/logrotate.conf
    failed_when: false
